language: java
jdk:
  - openjdk8

# branches
branch:
  only:
    - master

# Travis CI Repository
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
script: ./gradlew clean build

# deploy
before_deploy:
  - mkdir -p before-deploy # zip 에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/board.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings variable
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings variable
    bucket: board-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 로 설정
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings variable
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings variable
    bucket: board-build # s3 bucket
    key: board.zip
    bundle_type: zip
    application: board # codedeploy app name
    deployment_group: board-group # codedeploy group name
    region: ap-northeast-2
    wait-until-deployed: true

# notifications
notifications:
  email:
    recipients:
      - chunsang.yu@gmail.com